#!/bin/bash

dir=$(pwd -P)
cd util
unzip -nq javafx-sdk-11.0.2.zip
echo "Unzipped JavaFX"
jfxpath='util/javafx-sdk-11.0.2/lib'
cd ..
javac -d bin --module-path $jfxpath --add-modules javafx.controls src/tech/jriascos/*/*.java
echo "Compiled project."
echo "Running main found in tech.jriascos.application.Window"
java -classpath $dir/bin --module-path $jfxpath --add-modules javafx.controls tech.jriascos.application.Window
rm -rf util/javafx-sdk-11.0.2